[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
votingapplication = "5LdBsc82PTAfGCYg7q5z6ANbrjd7CnnVGbfetrEf4GRX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/mitch_1/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
